### ISSUE TITLE
[ Feature Request ] Dark Mode

### ISSUE THREAD

**Issue by aliglelo** [alexandrunastase/json-formatter-live#4]
I liked your work a lot and found it usable with just one problem and that is not having a **Dark Mode**. If you don't like the app to be dark-mode by default,you can give users a choice of choosing a theme by themselves.
Since, most of the developers now-a-days work with Dark-Mode Editor,extensions for browsers and optional dark interfaces available on the web,i think it would be a nice addition to the app.

**Comment by alexandrunastase** [comment]
Hey @aliglelo . Thanks for the suggestion. I will take that into consideration. Personally I haven't been using Dark mode for quite some time now, but this could be a nice addition. Plus the CSS needs a bit of cleanup :)

**Comment by aliglelo** [comment]
> Hey @aliglelo . Thanks for the suggestion. I will take that into consideration. Personally I haven't been using Dark mode for quite some time now, but this could be a nice addition. Plus the CSS needs a bit of cleanup :)

I'm glad you liked the idea.Thanks
